version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        - VITE_GITHUB_URL=${VITE_GITHUB_URL}
        - VITE_EMAIL_ADDRESS=${VITE_EMAIL_ADDRESS}
        - VITE_TELEGRAM_URL=${VITE_TELEGRAM_URL}
        - VITE_API_URL=${VITE_API_URL}
    image: ${DOCKER_USERNAME}/portfolio-frontend:latest