version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_USER}/portfolio-backend:latest
    ports:
      - "${BACKEND_HOST_PORT}:8000"
    networks:
      - network

  frontend:
    image: ${DOCKER_HUB_USER}/portfolio-frontend:latest
    ports:
      - "${FRONTEND_HOST_PORT}:80"
    depends_on:
      - backend
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge